// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.proto

package org.paboo.leaf.proto;

public final class LeafProto {
  private LeafProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeafReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeafReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeafResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeafResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nleaf.proto\",\n\007LeafReq\022\016\n\006nodeId\030\001 \001(\005\022" +
      "\021\n\tserviceId\030\002 \001(\005\"\026\n\010LeafResp\022\n\n\002id\030\001 \001" +
      "(\0032-\n\013LeafService\022\036\n\005IdGen\022\010.LeafReq\032\t.L" +
      "eafResp\"\000B&\n\024org.paboo.leaf.protoB\tLeafP" +
      "rotoP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LeafReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeafReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeafReq_descriptor,
        new java.lang.String[] { "NodeId", "ServiceId", });
    internal_static_LeafResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LeafResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeafResp_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
