// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.proto

package org.paboo.leaf.proto;

/**
 * Protobuf service {@code LeafService}
 */
public  abstract class LeafService
    implements com.google.protobuf.Service {
  protected LeafService() {}

  public interface Interface {
    /**
     * <code>rpc IdGen(.LeafReq) returns (.LeafResp);</code>
     */
    public abstract void idGen(
        com.google.protobuf.RpcController controller,
        org.paboo.leaf.proto.LeafReq request,
        com.google.protobuf.RpcCallback<org.paboo.leaf.proto.LeafResp> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new LeafService() {
      @java.lang.Override
      public  void idGen(
          com.google.protobuf.RpcController controller,
          org.paboo.leaf.proto.LeafReq request,
          com.google.protobuf.RpcCallback<org.paboo.leaf.proto.LeafResp> done) {
        impl.idGen(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.idGen(controller, (org.paboo.leaf.proto.LeafReq)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.paboo.leaf.proto.LeafReq.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.paboo.leaf.proto.LeafResp.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc IdGen(.LeafReq) returns (.LeafResp);</code>
   */
  public abstract void idGen(
      com.google.protobuf.RpcController controller,
      org.paboo.leaf.proto.LeafReq request,
      com.google.protobuf.RpcCallback<org.paboo.leaf.proto.LeafResp> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return org.paboo.leaf.proto.LeafProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.idGen(controller, (org.paboo.leaf.proto.LeafReq)request,
          com.google.protobuf.RpcUtil.<org.paboo.leaf.proto.LeafResp>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.paboo.leaf.proto.LeafReq.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.paboo.leaf.proto.LeafResp.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends org.paboo.leaf.proto.LeafService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void idGen(
        com.google.protobuf.RpcController controller,
        org.paboo.leaf.proto.LeafReq request,
        com.google.protobuf.RpcCallback<org.paboo.leaf.proto.LeafResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.paboo.leaf.proto.LeafResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          org.paboo.leaf.proto.LeafResp.class,
          org.paboo.leaf.proto.LeafResp.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public org.paboo.leaf.proto.LeafResp idGen(
        com.google.protobuf.RpcController controller,
        org.paboo.leaf.proto.LeafReq request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public org.paboo.leaf.proto.LeafResp idGen(
        com.google.protobuf.RpcController controller,
        org.paboo.leaf.proto.LeafReq request)
        throws com.google.protobuf.ServiceException {
      return (org.paboo.leaf.proto.LeafResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.paboo.leaf.proto.LeafResp.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:LeafService)
}

