// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.proto

package org.paboo.leaf.proto;

public interface LeafReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeafReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   */
  int getNodeId();

  /**
   * <code>int32 serviceId = 2;</code>
   */
  int getServiceId();
}
